#line 2 "lexer.c"

#line 4 "lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 33
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

int yylex_init (yyscan_t* scanner);

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef unsigned int yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 84
#define YY_END_OF_BUFFER 85
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[267] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       38,   38,    0,    0,   85,   29,   24,   23,   26,   28,
        3,   29,   29,   29,   20,   20,    1,    2,    4,   19,
       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       52,   43,   51,   52,   52,   52,   52,   61,   63,   62,
       55,   53,   84,   54,   60,   59,   56,   57,   65,   64,
       66,   68,   67,   69,   81,   82,   83,   71,   70,   72,
       74,   73,   75,   38,   39,   40,   37,   30,   84,   20,
       22,   27,   25,   22,   20,    0,    0,   19,   19,   19,

       19,   19,   19,   19,   19,   19,   19,   19,   19,   19,
       19,    0,    0,    0,    0,    0,    0,   61,   60,   58,
       65,   64,   68,   67,   81,   82,   83,    0,    0,   71,
       70,   74,   73,   38,   39,   40,   41,   40,   42,   37,
       36,   34,   35,   31,   33,   32,    0,   22,   25,    0,
       22,    0,   21,   19,   19,   19,   19,   19,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   78,    0,   22,   22,
        0,    0,    0,   19,   14,   19,   19,   19,   19,   19,
        6,   19,    5,   19,   19,   19,   17,    0,   48,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       22,   19,   19,   19,   18,   15,   13,   19,   19,   19,
       19,    0,   49,   44,    0,    0,   47,   79,    0,    0,
        0,    0,   22,   22,   11,   19,   19,   19,   19,   19,
       16,   46,   45,    0,   80,   77,    0,   22,   19,   19,
       19,   19,   19,   50,   76,   19,   19,   10,    8,    7,
       12,   19,   19,   19,    9,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    9,   10,   11,   12,   13,   14,
       15,   13,   13,   13,   13,   13,   13,   16,   17,   18,
       19,   20,    1,    1,   21,   21,   21,   21,   22,   23,
       24,   24,   24,   24,   24,   25,   24,   24,   24,   26,
       24,   24,   24,   24,   24,   24,   24,   27,   24,   24,
        1,   28,    1,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   24,   37,   24,   24,   38,   24,   39,
       40,   41,   42,   43,   44,   45,   46,   24,   24,   27,
       47,   24,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[48] =
    {   0,
        1,    2,    3,    4,    5,    6,    1,    1,    1,    7,
        1,    8,    8,    8,    8,    1,    1,    1,    1,    9,
        8,    8,    8,   10,   10,   10,   10,   11,   10,    8,
        8,    8,    8,    8,    8,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10
    } ;

static yyconst flex_int16_t yy_base[293] =
    {   0,
        0,    0,   46,   48,   49,   50,   52,   55,   68,   71,
       58,   60,   62,   64,   81,   84,   66,   95,   98,  100,
       87,  101,  102,  105,  622,  623,  623,  623,  623,  623,
      623,   98,  102,  112,  124,  130,  623,  623,  623,    0,
      589,  580,   85,   90,  580,  578,  587,  576,   90,  572,
      623,  623,  623,  580,   83,   90,  574,    0,  623,  623,
      623,  623,  623,  623,    0,  623,  623,  608,    0,  609,
      623,    0,  608,  623,    0,  606,  122,    0,  606,  623,
        0,  605,  623,  603,  623,  144,    0,  623,  118,  153,
      157,  623,    0,    0,  163,  174,  595,    0,  559,  563,

      570,  562,  562,  559,  553,  564,  553,  555,  152,  551,
      547,  557,  547,  557,  115,  557,  555,    0,    0,  623,
        0,  585,    0,  584,    0,  582,  579,  160,  538,    0,
      551,    0,  550,  530,  623,  190,  623,  197,  623,    0,
      623,  623,  623,  623,  623,  623,  197,  623,    0,  201,
      205,    0,  195,  482,  480,  468,  478,  455,  467,  471,
      451,  445,  429,  437,  420,  428,  421,  414,  293,  289,
      290,  290,  284,  287,  276,  286,  190,  212,  232,  623,
      100,  181,  247,  278,    0,  274,  272,  280,  267,  297,
        0,  272,    0,  277,  274,  268,    0,  267,  623,  265,

      264,  263,  250,  260,  260,  256,  258,  258,  259,  219,
      263,  251,  259,  253,    0,    0,    0,  247,  239,  244,
      246,  247,  623,  623,  245,  246,  623,  623,  234,  230,
      230,  236,  290,  623,    0,  218,  220,  219,  212,  210,
        0,  623,  623,  207,  623,  623,  204,  623,  198,  203,
      197,  159,  150,  623,  623,  131,  130,    0,    0,    0,
        0,  115,   91,   52,    0,  623,  328,  339,  350,  361,
      372,  383,  394,  405,  416,  427,  438,  442,  452,  462,
      472,  483,  494,  505,  516,  527,  538,  549,  559,  570,
      575,   68

    } ;

static yyconst flex_int16_t yy_def[293] =
    {   0,
      266,    1,  267,  267,  268,  268,  269,  269,  270,  270,
      271,  271,  272,  272,  273,  273,  274,  274,  275,  275,
      276,  276,  277,  277,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      266,  266,  266,  266,  266,  266,  266,  279,  266,  266,
      266,  266,  266,  266,  280,  266,  266,  266,  281,  266,
      266,  282,  266,  266,  283,  266,  266,  284,  266,  266,
      285,  266,  266,  286,  266,  287,  288,  266,  289,  266,
      266,  266,  290,   91,  266,  266,  291,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  266,  266,  266,  266,  266,  266,  279,  280,  266,
      281,  266,  282,  266,  283,  266,  266,  266,  266,  284,
      266,  285,  266,  286,  266,  287,  266,  287,  266,  288,
      266,  266,  266,  266,  266,  266,  266,  266,  290,  266,
      266,  292,  291,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      292,  292,  266,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  266,  266,  266,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  278,  278,  278,  278,  278,  278,
      278,  266,  266,  266,  266,  266,  266,  266,  278,  278,
      278,  278,  278,  266,  266,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,    0,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266

    } ;

static yyconst flex_int16_t yy_nxt[671] =
    {   0,
       26,   27,   28,   29,   30,   26,   26,   31,   32,   33,
       34,   35,   36,   36,   36,   37,   38,   26,   39,   26,
       40,   40,   40,   40,   40,   40,   40,   26,   40,   41,
       42,   40,   43,   40,   44,   40,   45,   40,   46,   40,
       47,   40,   48,   49,   50,   40,   40,   52,   53,   52,
       53,   59,   59,   62,   63,   64,   62,   63,   64,   70,
       71,   70,   71,   73,   74,   73,   74,   79,   80,   64,
       66,   67,   64,   66,   67,  181,   60,   60,   54,   55,
       54,   55,   56,   76,   56,   77,   76,   67,   77,   85,
       67,   57,   86,   57,  265,   68,   79,   80,   68,   82,

       83,   82,   83,   85,   63,   88,   86,   63,   88,   90,
       90,   90,   90,   91,   91,   91,   91,   92,  101,  103,
      113,  114,   93,  109,  115,  209,  127,  104,  116,   89,
      264,  102,   89,   94,  110,   95,   95,   95,   95,   94,
      209,   95,   95,   95,   95,   96,  137,  171,  142,  138,
       97,   96,  143,  172,  139,  128,  144,   96,  129,  263,
      145,  262,  146,   96,   90,   90,   90,   90,   91,   91,
       91,   91,   94,  261,   95,   95,   95,   95,  147,  148,
      150,  148,  150,  260,   96,  151,  151,  151,  151,  164,
      147,  148,  137,  165,  148,  266,   96,  175,  176,  137,

      266,  259,  138,  178,  182,  178,  209,  139,  179,  179,
      179,  179,  151,  151,  151,  151,  151,  151,  151,  151,
      183,  209,  207,  179,  179,  179,  179,  180,  208,  180,
      211,  211,  211,  211,  258,  183,  257,  256,  255,  180,
      254,  253,  180,  179,  179,  179,  179,  233,  233,  233,
      233,  252,  251,  210,  148,  210,  148,  250,  211,  211,
      211,  211,  249,  247,  246,  232,  148,  232,  245,  148,
      233,  233,  233,  233,  211,  211,  211,  211,  244,  243,
      242,  241,  240,  239,  238,  234,  237,  234,  236,  235,
      231,  230,  229,  228,  227,  226,  225,  234,  224,  223,

      234,  233,  233,  233,  233,  222,  221,  220,  219,  218,
      217,  216,  248,  215,  248,  214,  213,  212,  206,  205,
      204,  203,  202,  201,  248,  200,  199,  248,   51,   51,
       51,   51,   51,   51,   51,   51,   51,   51,   51,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   75,   75,   75,   75,   75,   75,

       75,   75,   75,   75,   75,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   78,   81,   81,   81,   81,
       81,   81,   81,   81,   81,   81,   81,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   87,   87,
       87,   87,   87,   87,   87,   87,   87,   87,   87,   98,
      198,   98,  118,  118,  197,  118,  118,  118,  118,  118,
      118,  118,  119,  119,  196,  195,  119,  119,  119,  119,
      194,  119,  121,  193,  192,  121,  121,  121,  121,  121,
      121,  121,  121,  123,  191,  190,  123,  123,  123,  123,
      123,  123,  123,  123,  125,  125,  189,  125,  188,  125,

      125,  125,  125,  125,  125,  130,  187,  186,  130,  130,
      130,  130,  130,  130,  130,  130,  132,  185,  184,  132,
      132,  132,  132,  132,  132,  132,  132,  134,  134,  134,
      134,  134,  135,  134,  134,  134,  134,  134,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  140,
      140,  133,  131,  140,  140,  140,  140,  140,  140,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  141,  141,
      149,  149,  177,  149,  149,  149,  149,  149,  149,  149,
      149,  153,  153,  127,  126,  124,  122,  174,  173,  170,
      169,  168,  167,  166,  163,  162,  161,  160,  159,  158,

      157,  156,  155,  154,  152,  135,  133,  131,  126,  124,
      122,  120,  117,  112,  111,  108,  107,  106,  105,  100,
       99,  266,   25,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266
    } ;

static yyconst flex_int16_t yy_chk[671] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    4,
        4,    5,    6,    7,    7,    7,    8,    8,    8,   11,
       11,   12,   12,   13,   13,   14,   14,   17,   17,    7,
        9,    9,    8,   10,   10,  292,    5,    6,    3,    3,
        4,    4,    3,   15,    4,   15,   16,    9,   16,   21,
       10,    3,   21,    4,  264,    9,   18,   18,   10,   19,

       19,   20,   20,   22,   23,   23,   22,   24,   24,   32,
       32,   32,   32,   33,   33,   33,   33,   34,   43,   44,
       55,   55,   34,   49,   56,  181,   77,   44,   56,   23,
      263,   43,   24,   35,   49,   35,   35,   35,   35,   36,
      181,   36,   36,   36,   36,   35,   86,  115,   89,   86,
       35,   36,   89,  115,   86,   77,   89,   35,   77,  262,
       89,  257,   89,   36,   90,   90,   90,   90,   91,   91,
       91,   91,   95,  256,   95,   95,   95,   95,   91,   91,
       96,   91,   96,  253,   95,   96,   96,   96,   96,  109,
       91,   91,  136,  109,   91,  136,   95,  128,  128,  138,

      136,  252,  138,  147,  153,  147,  182,  138,  147,  147,
      147,  147,  150,  150,  150,  150,  151,  151,  151,  151,
      153,  182,  177,  178,  178,  178,  178,  151,  177,  151,
      210,  210,  210,  210,  251,  153,  250,  249,  247,  151,
      244,  240,  151,  179,  179,  179,  179,  232,  232,  232,
      232,  239,  238,  183,  179,  183,  179,  237,  183,  183,
      183,  183,  236,  231,  230,  209,  179,  209,  229,  179,
      209,  209,  209,  209,  211,  211,  211,  211,  226,  225,
      222,  221,  220,  219,  218,  211,  214,  211,  213,  212,
      208,  207,  206,  205,  204,  203,  202,  211,  201,  200,

      211,  233,  233,  233,  233,  198,  196,  195,  194,  192,
      190,  189,  233,  188,  233,  187,  186,  184,  176,  175,
      174,  173,  172,  171,  233,  170,  169,  233,  267,  267,
      267,  267,  267,  267,  267,  267,  267,  267,  267,  268,
      268,  268,  268,  268,  268,  268,  268,  268,  268,  268,
      269,  269,  269,  269,  269,  269,  269,  269,  269,  269,
      269,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  271,  271,  271,  271,  271,  271,  271,  271,
      271,  271,  271,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  273,  273,  273,  273,  273,  273,

      273,  273,  273,  273,  273,  274,  274,  274,  274,  274,
      274,  274,  274,  274,  274,  274,  275,  275,  275,  275,
      275,  275,  275,  275,  275,  275,  275,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  278,
      168,  278,  279,  279,  167,  279,  279,  279,  279,  279,
      279,  279,  280,  280,  166,  165,  280,  280,  280,  280,
      164,  280,  281,  163,  162,  281,  281,  281,  281,  281,
      281,  281,  281,  282,  161,  160,  282,  282,  282,  282,
      282,  282,  282,  282,  283,  283,  159,  283,  158,  283,

      283,  283,  283,  283,  283,  284,  157,  156,  284,  284,
      284,  284,  284,  284,  284,  284,  285,  155,  154,  285,
      285,  285,  285,  285,  285,  285,  285,  286,  286,  286,
      286,  286,  134,  286,  286,  286,  286,  286,  287,  287,
      287,  287,  287,  287,  287,  287,  287,  287,  287,  288,
      288,  133,  131,  288,  288,  288,  288,  288,  288,  289,
      289,  289,  289,  289,  289,  289,  289,  289,  289,  289,
      290,  290,  129,  290,  290,  290,  290,  290,  290,  290,
      290,  291,  291,  127,  126,  124,  122,  117,  116,  114,
      113,  112,  111,  110,  108,  107,  106,  105,  104,  103,

      102,  101,  100,   99,   97,   84,   82,   79,   76,   73,
       70,   68,   57,   54,   50,   48,   47,   46,   45,   42,
       41,   25,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[85] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 
    0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 
    0, 0, 1, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "libs\\btree\\source\\parser\\lexer.l"
/* 
 * 
 * Copyright (C) 2009, Joacim Jacobsson ( j dot jacobsson at gmail dot com ) 
 * All rights reserved.
 * 
 * See LICENSE file for details
 * 
 */
#define YY_NO_UNISTD_H 1
#line 20 "libs\\btree\\source\\parser\\lexer.l"

#include "common.h"
#include <stdio.h>
#define YY_INPUT(inBuffer, outResult, inMaxSize) ((outResult) = fill_lex_buffer( yyget_extra(yyscanner), (inBuffer), (inMaxSize)))

#define EOF_DANCE                                                           \
    {                                                                       \
        ParserContext* ctx = yyget_extra(yyscanner);                        \
        if( ctx->m_PPCurrScope != 0 ) {                                     \
            yyerror( ctx, yyscanner, "#if/#endif miss-match." );            \
            yyterminate();                                                  \
        }                                                                   \
        else if( pop_parse_file( ctx ) )                                    \
            return T_END_OF_FILE;                                           \
    }                                                                       \
        
        




#line 731 "lexer.c"

#define INITIAL 0
#define preprocessor 1
#define pp_eat_statement 2
#define pp_include 3
#define pp_inc_string 4
#define pp_ifdef 5
#define pp_ifndef 6
#define pp_eat_until 7
#define pp_define 8
#define pp_undef 9
#define ml_comment 10
#define string 11

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    int yy_n_chars;
    int yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

int yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

YYSTYPE * yyget_lval (yyscan_t yyscanner );

void yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  ,yyscan_t yyscanner);
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int yylex (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 71 "libs\\btree\\source\\parser\\lexer.l"


#line 972 "lexer.c"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 267 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 266 );
		yy_cp = yyg->yy_last_accepting_cpos;
		yy_current_state = yyg->yy_last_accepting_state;

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case YY_STATE_EOF(INITIAL):
#line 73 "libs\\btree\\source\\parser\\lexer.l"
{ EOF_DANCE; }
	YY_BREAK
case 1:
YY_RULE_SETUP
#line 76 "libs\\btree\\source\\parser\\lexer.l"
{ return T_COLON; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 77 "libs\\btree\\source\\parser\\lexer.l"
{ return T_SEMICOLON; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 78 "libs\\btree\\source\\parser\\lexer.l"
{ return T_COMMA; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 79 "libs\\btree\\source\\parser\\lexer.l"
{ return T_ASSIGNMENT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 80 "libs\\btree\\source\\parser\\lexer.l"
{ return T_ROOT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 81 "libs\\btree\\source\\parser\\lexer.l"
{ return T_NODE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 82 "libs\\btree\\source\\parser\\lexer.l"
{ return T_SEQUENCE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 83 "libs\\btree\\source\\parser\\lexer.l"
{ return T_SELECTOR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "libs\\btree\\source\\parser\\lexer.l"
{ return T_DSELECTOR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 85 "libs\\btree\\source\\parser\\lexer.l"
{ return T_PARALLEL; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 86 "libs\\btree\\source\\parser\\lexer.l"
{ return T_ACTION; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 87 "libs\\btree\\source\\parser\\lexer.l"
{ return T_DECORATOR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 88 "libs\\btree\\source\\parser\\lexer.l"
{ return T_INT32; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 89 "libs\\btree\\source\\parser\\lexer.l"
{ return T_BOOL; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 90 "libs\\btree\\source\\parser\\lexer.l"
{ return T_FLOAT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 91 "libs\\btree\\source\\parser\\lexer.l"
{ return T_STRING; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 92 "libs\\btree\\source\\parser\\lexer.l"
{ yylval->m_Integer = 1; return T_BOOL_VALUE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 93 "libs\\btree\\source\\parser\\lexer.l"
{ yylval->m_Integer = 0; return T_BOOL_VALUE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 94 "libs\\btree\\source\\parser\\lexer.l"
{
                    ParserContext* ctx = yyget_extra(yyscanner); 
                    (*yylval).m_Id = ctx->m_Tree->CreateId( yytext, yylineno );
                    return T_ID; 
                }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 99 "libs\\btree\\source\\parser\\lexer.l"
{
                    sscanf( yytext, "%d", &((*yylval).m_Integer) ); 
                    return T_INT32_VALUE;
                }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 103 "libs\\btree\\source\\parser\\lexer.l"
{
                    sscanf( yytext, "%x", &((*yylval).m_Integer) ); 
                    return T_INT32_VALUE;
                }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 107 "libs\\btree\\source\\parser\\lexer.l"
{
                    sscanf( yytext, "%f", &((*yylval).m_Float) );
                    return T_FLOAT_VALUE;
                }
	YY_BREAK
case 23:
/* rule 23 can match eol */
YY_RULE_SETUP
#line 111 "libs\\btree\\source\\parser\\lexer.l"
{ /* eat newlines, or they get echoed to the screen... */ }             
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 112 "libs\\btree\\source\\parser\\lexer.l"
{ /* eat whitespace */ }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 115 "libs\\btree\\source\\parser\\lexer.l"
{ /* eat single line comments */ }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 117 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(string); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 118 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(ml_comment); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 119 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(preprocessor); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 120 "libs\\btree\\source\\parser\\lexer.l"
{ yyerror( yyget_extra(yyscanner), yyscanner, "unrecognized character." ); }
	YY_BREAK

case 30:
YY_RULE_SETUP
#line 123 "libs\\btree\\source\\parser\\lexer.l"
{   /*closing quote*/
                    BEGIN(INITIAL);
                    ParserContext* ctx = yyget_extra(yyscanner );
                    (*yylval).m_String  = ctx->m_Tree->RegisterString( ctx->m_TmpString.c_str() );
                    ctx->m_TmpString    = "";
                    return T_STRING_VALUE;
                }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 130 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner)->m_TmpString += '\n'; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 131 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner)->m_TmpString += '\t'; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 132 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner)->m_TmpString += '\r'; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 133 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner)->m_TmpString += '\b'; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 134 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner)->m_TmpString += '\f'; }
	YY_BREAK
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 136 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner)->m_TmpString += yytext[1]; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 138 "libs\\btree\\source\\parser\\lexer.l"
{
                    yyget_extra(yyscanner)->m_TmpString += yytext;
                }
	YY_BREAK
case YY_STATE_EOF(string):
#line 141 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    yyerror( yyget_extra(yyscanner), yyscanner, "end of file in string constant" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }
	YY_BREAK


case 38:
YY_RULE_SETUP
#line 149 "libs\\btree\\source\\parser\\lexer.l"
{ }
	YY_BREAK
case 39:
/* rule 39 can match eol */
YY_RULE_SETUP
#line 150 "libs\\btree\\source\\parser\\lexer.l"
{ }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 151 "libs\\btree\\source\\parser\\lexer.l"
{ }
	YY_BREAK
case 41:
/* rule 41 can match eol */
YY_RULE_SETUP
#line 152 "libs\\btree\\source\\parser\\lexer.l"
{ }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 153 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(INITIAL); }
	YY_BREAK


case 43:
YY_RULE_SETUP
#line 157 "libs\\btree\\source\\parser\\lexer.l"
{ /* eat whitespace */ }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 158 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(pp_ifdef); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 159 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(pp_ifndef); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 160 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(pp_define); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 161 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(pp_undef); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 162 "libs\\btree\\source\\parser\\lexer.l"
{
                    ParserContext* ctx = yyget_extra(yyscanner );
                    if( ctx->m_PPCurrScope == 0 )
                    {
                        yyerror( yyget_extra(yyscanner), yyscanner, "mis-matching #ifdef/#else/#endif" ); 
                        BEGIN(INITIAL);
                        yyterminate(); 
                    }
                    ctx->m_PPUntilScope = ctx->m_PPCurrScope;
                    BEGIN(pp_eat_until); 
                }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 173 "libs\\btree\\source\\parser\\lexer.l"
{
                    ParserContext* ctx = yyget_extra(yyscanner );
                    if( ctx->m_PPCurrScope == 0 )
                    {
                        yyerror( yyget_extra(yyscanner), yyscanner, "mis-matching #ifdef/#else/#endif" ); 
                        BEGIN(INITIAL);
                        yyterminate(); 
                    }
                    ctx->m_PPCurrScope--; 
                    BEGIN(INITIAL);
                }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 184 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(pp_include); }
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 185 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    yyerror( yyget_extra(yyscanner), yyscanner, yyget_lineno(yyscanner) - 1, "invalid pre-processor directive" );
                    BEGIN(INITIAL);
                }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 189 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(pp_eat_statement); yyless(0); }
	YY_BREAK
case YY_STATE_EOF(preprocessor):
#line 190 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    yyerror( yyget_extra(yyscanner), yyscanner, "end of file in pre-processor directive" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }
	YY_BREAK


case 53:
YY_RULE_SETUP
#line 198 "libs\\btree\\source\\parser\\lexer.l"
{ /* eat whitespace */ }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 199 "libs\\btree\\source\\parser\\lexer.l"
{ BEGIN(pp_inc_string); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 200 "libs\\btree\\source\\parser\\lexer.l"
{   
                    yyerror( yyget_extra(yyscanner), yyscanner, "invalid include statement" ); 
                    BEGIN(INITIAL);
                    yyterminate();
                }
	YY_BREAK


case 56:
YY_RULE_SETUP
#line 208 "libs\\btree\\source\\parser\\lexer.l"
{   /*closing quote*/
                    /* setup the buffer here */
                    ParserContext* ctx = yyget_extra(yyscanner );
                    push_parse_file( ctx, ctx->m_TmpString.c_str() );
                    ctx->m_TmpString = "";
                    BEGIN(INITIAL);
                }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 215 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner)->m_TmpString += '/'; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 216 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner)->m_TmpString += '"'; }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 218 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    yyerror( yyget_extra(yyscanner), yyscanner, yyget_lineno(yyscanner) - 1, "include strings cannot span multiple lines" ); 
                    BEGIN(INITIAL);
                    yyterminate();  
                }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 223 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner)->m_TmpString += yytext; }
	YY_BREAK
case YY_STATE_EOF(pp_inc_string):
#line 224 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    yyerror( yyget_extra(yyscanner), yyscanner, "end of file in include string" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }
	YY_BREAK


case 61:
YY_RULE_SETUP
#line 232 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner )->m_TmpString += yytext; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 233 "libs\\btree\\source\\parser\\lexer.l"
{ yyget_extra(yyscanner )->m_NewLines++; yyget_extra(yyscanner )->m_TmpString += yytext; }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 234 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    ParserContext* ctx = yyget_extra(yyscanner );
                    if( ctx->m_NewLines == 0 )
                    {
                        char tmp[2048];
                        sprintf( tmp, "unknown preprocessor directive:\n\t#%s", ctx->m_TmpString.c_str() );
                        yywarning( ctx, yyscanner, yyget_lineno(yyscanner) - 1, tmp );
                        ctx->m_TmpString = "";
                        BEGIN(INITIAL);
                    } 
                    else
                    {
                        ctx->m_TmpString += '\n';
                        ctx->m_TmpString += '\t';
                        ctx->m_NewLines--;
                    }
                }
	YY_BREAK
case YY_STATE_EOF(pp_eat_statement):
#line 251 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    ParserContext* ctx = yyget_extra(yyscanner );
                    char tmp[2048];
                    sprintf( tmp, "unknown preprocessor directive:\n\t#%s", ctx->m_TmpString.c_str() );
                    yywarning( ctx, yyscanner, tmp );
                    ctx->m_TmpString    = "";
                    ctx->m_NewLines     = 0;
                    BEGIN(INITIAL);
                    EOF_DANCE;
                }
	YY_BREAK
//end of the <pp_eat_statement> family of rules

case 64:
YY_RULE_SETUP
#line 264 "libs\\btree\\source\\parser\\lexer.l"
{ /* eat the white-space */ }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 265 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    ParserContext* ctx = yyget_extra(yyscanner );
                    ctx->m_PPCurrScope++;
                    if( ctx->m_Tree->IsDefined( yytext ) )
                    {
                        BEGIN(INITIAL);                     
                    }
                    else
                    {
                        ctx->m_PPUntilScope = ctx->m_PPCurrScope - 1;
                        BEGIN(pp_eat_until);
                    }
                }
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 278 "libs\\btree\\source\\parser\\lexer.l"
{
                    yyerror( yyget_extra(yyscanner), yyscanner, "unexpected newline in #ifdef directive" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }               
	YY_BREAK
case YY_STATE_EOF(pp_ifdef):
#line 283 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    yyerror( yyget_extra(yyscanner), yyscanner, "end of file #ifdef directive" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }
	YY_BREAK


case 67:
YY_RULE_SETUP
#line 291 "libs\\btree\\source\\parser\\lexer.l"
{ /* eat the white-space */ }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 292 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    ParserContext* ctx = yyget_extra(yyscanner );
                    ctx->m_PPCurrScope++;
                    if( ctx->m_Tree->IsDefined( yytext ) )
                    {
                        ctx->m_PPUntilScope = ctx->m_PPCurrScope - 1;
                        BEGIN(pp_eat_until);
                    }
                    else
                    {
                        BEGIN(INITIAL);
                    }
                }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 305 "libs\\btree\\source\\parser\\lexer.l"
{
                    yyerror( yyget_extra(yyscanner), yyscanner, "unexpected newline in #ifndef directive" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }               
	YY_BREAK
case YY_STATE_EOF(pp_ifndef):
#line 310 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    yyerror( yyget_extra(yyscanner), yyscanner, "end of file #ifndef directive" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }
	YY_BREAK


case 70:
YY_RULE_SETUP
#line 317 "libs\\btree\\source\\parser\\lexer.l"
{ /* eat the white-space */ }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 318 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    ParserContext* ctx = yyget_extra(yyscanner );
                    ctx->m_Tree->Define( yytext );
                    BEGIN(INITIAL);
                }
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 323 "libs\\btree\\source\\parser\\lexer.l"
{
                    yyerror( yyget_extra(yyscanner), yyscanner, "unexpected newline in #define directive" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }               
	YY_BREAK
case YY_STATE_EOF(pp_define):
#line 328 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    yyerror( yyget_extra(yyscanner), yyscanner, "end of file #define directive" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }
	YY_BREAK


case 73:
YY_RULE_SETUP
#line 335 "libs\\btree\\source\\parser\\lexer.l"
{ /* eat the white-space */ }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 336 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    ParserContext* ctx = yyget_extra(yyscanner );
                    ctx->m_Tree->Undefine( yytext );
                    BEGIN(INITIAL);
                }
	YY_BREAK
case 75:
/* rule 75 can match eol */
YY_RULE_SETUP
#line 341 "libs\\btree\\source\\parser\\lexer.l"
{
                    yyerror( yyget_extra(yyscanner), yyscanner, "unexpected newline in #undef directive" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }               
	YY_BREAK
case YY_STATE_EOF(pp_undef):
#line 346 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    yyerror( yyget_extra(yyscanner), yyscanner, "end of file #undef directive" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }
	YY_BREAK


case 76:
#line 355 "libs\\btree\\source\\parser\\lexer.l"
case 77:
#line 356 "libs\\btree\\source\\parser\\lexer.l"
case 78:
YY_RULE_SETUP
#line 356 "libs\\btree\\source\\parser\\lexer.l"
{
                    ParserContext* ctx = yyget_extra(yyscanner );
                    ctx->m_PPCurrScope++;
                }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 360 "libs\\btree\\source\\parser\\lexer.l"
{
                    ParserContext* ctx = yyget_extra(yyscanner );
                    if( ctx->m_PPCurrScope == ctx->m_PPUntilScope + 1 )
                        BEGIN(INITIAL);
                }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 365 "libs\\btree\\source\\parser\\lexer.l"
{
                    ParserContext* ctx = yyget_extra(yyscanner );
                    ctx->m_PPCurrScope--;
                    if( ctx->m_PPCurrScope == ctx->m_PPUntilScope )
                        BEGIN(INITIAL);
                }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 371 "libs\\btree\\source\\parser\\lexer.l"
{ /* just eat it */ }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 372 "libs\\btree\\source\\parser\\lexer.l"
{ /* just eat it */ }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 373 "libs\\btree\\source\\parser\\lexer.l"
{ /* just eat it */ }
	YY_BREAK
case YY_STATE_EOF(pp_eat_until):
#line 374 "libs\\btree\\source\\parser\\lexer.l"
{ 
                    yyerror( yyget_extra(yyscanner), yyscanner, "#ifdef/#ifndef statements cannot span several files" ); 
                    BEGIN(INITIAL);
                    yyterminate(); 
                }
	YY_BREAK

case 84:
YY_RULE_SETUP
#line 381 "libs\\btree\\source\\parser\\lexer.l"
ECHO;
	YY_BREAK
#line 1728 "lexer.c"
case YY_STATE_EOF(pp_include):
case YY_STATE_EOF(ml_comment):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_last_accepting_cpos;
				yy_current_state = yyg->yy_last_accepting_state;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 267 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 267 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 266);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp , yyscan_t yyscanner)
{
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    yy_cp = yyg->yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yyg->yy_hold_char;

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yyg->yy_n_chars + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	yyg->yytext_ptr = yy_bp;
	yyg->yy_hold_char = *yy_cp;
	yyg->yy_c_buf_p = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	int num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param str a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
int yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_lineno called with no buffer" , yyscanner); 
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           yy_fatal_error( "yyset_column called with no buffer" , yyscanner); 
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 381 "libs\\btree\\source\\parser\\lexer.l"



int fill_lex_buffer( ParserContext* ctx, char* buffer, int maxsize )
{
    if( !ctx->m_File )
        return 0;
        
    if( feof( ctx->m_File->m_File ) )
        return 0;
    
    size_t read = fread( buffer, 1, maxsize, ctx->m_File->m_File );
    return read;
}

bool push_parse_file( ParserContext* ctx, const char* filename )
{
    int len = strlen( filename );
    if( len > 2047 )
        return false;

    ParseFile* file = ctx->m_Tree->CreateParseFile();
    memcpy( file->m_Name, filename, len+1 );
    file->m_File    = fopen( file->m_Name, "r" );
    file->m_Buffer  = 0x0;
    file->m_Next    = ctx->m_File;
    
    if( !file->m_File )
    {
        char tmp[4096];
        sprintf( tmp, "unable to open input file \"%s\"", filename );
        yyerror( ctx, ctx->yyscanner, tmp );
        ctx->m_Tree->FreeParseFile( file );
        return false;
    }

    file->m_Buffer = yy_create_buffer(file->m_File,YY_BUF_SIZE,ctx->yyscanner );
    yy_switch_to_buffer(file->m_Buffer,ctx->yyscanner );  

    ctx->m_File = file;

    return true;
}

bool pop_parse_file( ParserContext* ctx )
{
    if( !ctx || !ctx->m_File )
        return true;
        
    ParseFile* file = ctx->m_File;
    ctx->m_File     = file->m_Next;

    if( ctx->m_File )
        yy_switch_to_buffer(ctx->m_File->m_Buffer,ctx->yyscanner );

    fclose( file->m_File );
    yy_delete_buffer(file->m_Buffer,ctx->yyscanner );

    ctx->m_Tree->FreeParseFile( file );

    return ctx->m_File == 0x0 ? true : false;   
}



